project:
  name: ec2-free-tier

  regions:
    - us-east-1

  package_lambda: false

tests:
  t2micro:
    template: templates/ec2.yaml

    parameters:
      VpcId: $[taskcat_getval(DefaultVpcId)]
      SubnetId: $[taskcat_getval(DefaultSubnet1Id)]
      InstanceType: t2.micro

    regions:
      - us-east-1