AWSTemplateFormatVersion: '2010-09-09'

Description: Amazon Linux 2023 Free Tier EC2 with SSM Access

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Networking
        Parameters:
          - VpcId
          - SubnetId

      - Label:
          default: EC2 Settings
        Parameters:
          - InstanceType

Parameters:

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

  VpcId:
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Type: AWS::EC2::Subnet::Id

  InstanceType:
    Type: String
    Default: t2.micro

    AllowedValues:
      - t2.micro
      - t3.micro

Resources:

  EC2Role:
    Type: AWS::IAM::Role

    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: AWS managed policy required for Session Manager

    Properties:

      AssumeRolePolicyDocument:
        Version: '2012-10-17'

        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile

    Properties:
      Roles:
        - !Ref EC2Role

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup

    Properties:

      GroupDescription: Outbound access only

      VpcId: !Ref VpcId

      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sg"

  EC2Instance:
    Type: AWS::EC2::Instance

    Properties:

      ImageId: !Ref LatestAmiId

      InstanceType: !Ref InstanceType

      SubnetId: !Ref SubnetId

      SecurityGroupIds:
        - !Ref SecurityGroup

      IamInstanceProfile: !Ref EC2InstanceProfile

      MetadataOptions:
        HttpTokens: required

      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-instance"

        - Key: Environment
          Value: Learning

        - Key: ManagedBy
          Value: CloudFormation

Outputs:

  InstanceId:
    Value: !Ref EC2Instance

  PrivateIP:
    Value: !GetAtt EC2Instance.PrivateIp

  AvailabilityZone:
    Value: !GetAtt EC2Instance.AvailabilityZone

  RoleName:
    Value: !Ref EC2Role