name: Validate CloudFormation

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  id-token: write
  contents: read

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "setuptools<81"
          pip install -r requirements.txt

      - name: Verify Files
        run: |
          pwd
          ls -la
          find . -type f | sort

      - name: Run cfn-lint
        run: |
          cfn-lint templates/ec2.yaml

      - name: Install cfn-guard
        run: |
          #VERSION=3.1.2
          wget https://github.com/aws-cloudformation/cloudformation-guard/releases/download/3.2.0/cfn-guard-v3-x86_64-linux-latest.tar.gz
          #wget https://github.com/aws-cloudformation/cloudformation-guard/releases/download/${VERSION}/cfn-guard-v${VERSION}-x86_64-unknown-linux-musl.tar.gz
          #tar -xzf cfn-guard-v${VERSION}-x86_64-unknown-linux-musl.tar.gz
          tar -xzf cfn-guard-v3-x86_64-linux-latest.tar.gz
          chmod +x cfn-guard-v3-x86_64-linux-latest/cfn-guard
          sudo mv cfn-guard-v3-x86_64-linux-latest/cfn-guard /usr/local/bin/cfn-guard
          #curl --proto '=https' --tlsv1.2 -sSf \
            https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh \
            | sh

          #echo "$HOME/.guard/bin" >> $GITHUB_PATH

      - name: Verify cfn-guard
        run: |
          cfn-guard --version

      - name: Run cfn-guard
        run: |
          cfn-guard validate \
            --rules guard \
            --data templates/ec2.yaml

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install cfn-nag
        run: |
          gem install cfn-nag

      - name: Verify cfn-nag
        run: |
          cfn_nag_scan --version

      - name: Run cfn-nag
        run: |
          cfn_nag_scan \
            --input-path templates/ec2.yaml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Verify Network
        run: |
          echo "Default VPC"

          aws ec2 describe-vpcs \
            --filters Name=is-default,Values=true \
            --region us-east-1

          echo "Default Subnets"

          aws ec2 describe-subnets \
            --region us-east-1 \
            --filters Name=default-for-az,Values=true

      - name: Run TaskCat
        run: |
          taskcat test run

      - name: Upload TaskCat Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: taskcat-results
          path: |
            .taskcat_outputs

      - name: Dump TaskCat Output
        if: always()
        run: |
          find .taskcat_outputs -type f -exec echo "==== {} ====" \; -exec cat {} \; || true